"""文档归属声明源（**机器生成**：`python scripts/doc_ownership_sync.py --generate`）。

来源 = `docs/boards/_meta/doc-classification-20260921.md` 的机械投影（含基目录补全，
规则表住 `scripts/doc_ownership_sync.py`）+ `.superpowers` 目录级认领 + 板块生成页路径直取。
board=="" = 表内在册但**未归属**（NONE/空），不发明归属；路径已不存在的历史行在 DOC_OWNERSHIP_ARCHIVE。
手改本文件必被 `--check`/常驻门打回——要改账就改分类表再重投影（一处变更处处跟随）。
"""

from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class DocOwner:
    """一条归属 = (相对路径, 主板块 BNN, 二级 fid 或空, 现役性, 依据)。目录级 path 以 / 结尾。"""

    path: str
    board: str
    fid: str
    currency: str
    basis: str
    completed: bool = False

#: 目录级认领条目（.superpowers 波次目录等）——归属按最长前缀反查。
DOC_OWNERSHIP_DIRS: tuple[DocOwner, ...] = (
    DocOwner(path='.superpowers/sdd/2026-09-12-shorekeeper-global-audit/', board='B10', fid='', currency='过程件为主(fix-*-report/brief 逐号 + final-review-report + baseline-perf + 2 份 .diff)', basis='文件命名全为「席位报告」形态；有 .diff 说明含施工原稿', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-13-six-domain-batch/', board='B10', fid='', currency='过程件(*-report 逐席 + FINAL-REPORT-draft + RESUME)', basis='目录内 76 份 .md 全为席报; 含 1 份 .py(取证脚本)随目录一起走｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-13-six-domain-batch//', board='B10', fid='', currency='过程件(*-report 逐席 + FINAL-REPORT-draft + RESUME)', basis='目录内 76 份 .md 全为席报; 含 1 份 .py(取证脚本)随目录一起走｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-18-unify-wave/', board='B08', fid='', currency='**规格件 + 过程件混合**(master-plan.md 为主计划, commit-checklist.md 为待提交清单, progress-*.md 45+ 份席账)', basis='AGENTS #41 明文「未 commit——工作树逐文件显式 add 清单见 …/commit-checklist.md」｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-18-unify-wave//', board='B08', fid='', currency='**规格件 + 过程件混合**(master-plan.md 为主计划, commit-checklist.md 为待提交清单, progress-*.md 45+ 份席账)', basis='AGENTS #41 明文「未 commit——工作树逐文件显式 add 清单见 …/commit-checklist.md」｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-19-emergency-info-unify/', board='B05', fid='', currency='过程件 + 数据件(planning-with-files 三件套 + 5 .json + 1 .geojson + 1 .sh + .diff)', basis='顶层三件 findings/progress/task_plan 为 planning-with-files 会话产物形态｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-19-emergency-info-unify//', board='B05', fid='', currency='过程件 + 数据件(planning-with-files 三件套 + 5 .json + 1 .geojson + 1 .sh + .diff)', basis='顶层三件 findings/progress/task_plan 为 planning-with-files 会话产物形态｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-19-unify-audit/', board='B06', fid='', currency='**Wave G/H TTS 波档案**: plan-G-contract.md(规格真身之一) + briefs*.md + report-T10…T121 逐席 + closeout-manifest.md + 两份 -DRAFT', basis='AGENTS #44 明文把这两件当现役验收/规格入口用｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-19-unify-audit//', board='B06', fid='', currency='**Wave G/H TTS 波档案**: plan-G-contract.md(规格真身之一) + briefs*.md + report-T10…T121 逐席 + closeout-manifest.md + 两份 -DRAFT', basis='AGENTS #44 明文把这两件当现役验收/规格入口用｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-20-spec-audit/', board='B02', fid='', currency='过程件(audit-SA*/FIX*/IALERT/IGEN2/ISYNC 席 log) + 1 份 directive-capability-contract.md(指令件)', basis='文件首行命名法为审计/修复席位；无 master-plan 即非波次总纲｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-20-spec-audit//', board='B02', fid='', currency='过程件(audit-SA*/FIX*/IALERT/IGEN2/ISYNC 席 log) + 1 份 directive-capability-contract.md(指令件)', basis='文件首行命名法为审计/修复席位；无 master-plan 即非波次总纲｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-20-unify-fix-wave/', board='B10', fid='', currency='过程件(master-plan.md + progress.md + 34 份席 log)', basis='仅两件顶层总纲，席 log 为其拆解｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-20-unify-fix-wave//', board='B10', fid='', currency='过程件(master-plan.md + progress.md + 34 份席 log)', basis='仅两件顶层总纲，席 log 为其拆解｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-21-fix-wave/', board='B10', fid='', currency='**现役**: master-plan.md（§捌＝交接态四态表/禁碰面/证据地图/复跑命令簿）+ uncommitted-inventory.md + impl-WP1…WP11B 逐工作包 log', basis='AGENTS #47 明文「逐符号明细与未提交全量清单见 …/master-plan.md §捌 + uncommitted-inventory.md」｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-21-fix-wave//', board='B10', fid='', currency='**现役**: master-plan.md（§捌＝交接态四态表/禁碰面/证据地图/复跑命令簿）+ uncommitted-inventory.md + impl-WP1…WP11B 逐工作包 log', basis='AGENTS #47 明文「逐符号明细与未提交全量清单见 …/master-plan.md §捌 + uncommitted-inventory.md」｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-21-unify-consolidation/', board='B10', fid='', currency='过程件(deep-D1…D6/E1…E6 + line-1…11 逐条线 log + findings.md)', basis='单文件均值偏大（体量以现算为准，属最大目录之一），说明仍在写；无 master-plan 顶层件｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-21-unify-consolidation//', board='B10', fid='', currency='过程件(deep-D1…D6/E1…E6 + line-1…11 逐条线 log + findings.md)', basis='单文件均值偏大（体量以现算为准，属最大目录之一），说明仍在写；无 master-plan 顶层件｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-23-audit-8f099879/', board='B10', fid='', currency='过程件（八F09 审计席 log）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-23-audit2-8f099879/', board='B10', fid='', currency='过程件（BRIEFS/SEAT-A* 席报 + ledger 派发账）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-23-boards-full-doc-wave/', board='B10', fid='', currency='过程件（十板块文档波单件）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-23-modality-integration/', board='B10', fid='', currency='过程件（单件）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-23-stopfix-wave/', board='B10', fid='', currency='过程件（停摆根修波席 log）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-24-central-dispatch/', board='B10', fid='', currency='过程件 + **BASELINE.md 现役尺**（多门按其重算）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-24-cutover/', board='B10', fid='', currency='过程件（2 件）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-24-r2/', board='B10', fid='', currency='过程件', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-25-blindgate-census/', board='B10', fid='', currency='过程件（单件普查）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-25-gateway-telemetry/', board='B10', fid='', currency='过程件', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-25-goal18-wave/', board='B10', fid='', currency='过程件（十八项首窗席 log）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-25-safetyexec-review/', board='B10', fid='', currency='过程件（单件评审）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-26-goal18-second/', board='B10', fid='', currency='过程件（第二窗席 log）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-26-kb-recovery/', board='B10', fid='', currency='过程件（KB 恢复席 log）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-26-unify2/', board='B10', fid='', currency='过程件（单件）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-27-bughunt/', board='B10', fid='', currency='过程件（单件）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-27-fullload/', board='B10', fid='', currency='过程件（满载波席 log；SEAT-R8-TRIGGER-c.md 等）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-27-kb-grounding/', board='B10', fid='', currency='过程件（单件）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/FRONTEND-AUDIT/', board='B08', fid='', currency='评审件(review-*-report + 6 份 .diff 复核原稿)', basis='目录名与那批席报的引用路径逐字对应｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/FRONTEND-AUDIT//', board='B08', fid='', currency='评审件(review-*-report + 6 份 .diff 复核原稿)', basis='目录名与那批席报的引用路径逐字对应｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/emergency-info-registration-runbook-20260920/', board='B05', fid='', currency='过程件(progress.md 总账 + reports/ 十席 log + 14 .txt 探针输出)', basis='AGENTS #45 与施工图 §4 口径更正段两处引用本目录｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/emergency-info-registration-runbook-20260920//', board='B05', fid='', currency='过程件(progress.md 总账 + reports/ 十席 log + 14 .txt 探针输出)', basis='AGENTS #45 与施工图 §4 口径更正段两处引用本目录｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/news-card-samples/', board='B05', fid='', currency='样例件（快报卡样例 1 md）', basis='S-BASE 目录级判定 2026-09-29', completed=False),
    DocOwner(path='.superpowers/sdd/v21-20260917-parallel/', board='B10', fid='', currency='过程件(w1-affinity/w2-gates-baseline/w4-supervisor/w5-billing/w6-divination/w7-search 六席)', basis='六件同名「w<号>-<域>.md」=并行席位分账｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/v21-20260917-parallel//', board='B10', fid='', currency='过程件(w1-affinity/w2-gates-baseline/w4-supervisor/w5-billing/w6-divination/w7-search 六席)', basis='六件同名「w<号>-<域>.md」=并行席位分账｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/v21r6-audit/', board='B10', fid='', currency='过程件(audit-A-v21r5 / B-frontend / C-external2 / D-newfailures / audit-report / progress)', basis='目录名与根文件 HANDOFF-V21R6-TESTING.md 不同路径，易混为重复件但实非同一物｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/v21r6-audit//', board='B10', fid='', currency='过程件(audit-A-v21r5 / B-frontend / C-external2 / D-newfailures / audit-report / progress)', basis='目录名与根文件 HANDOFF-V21R6-TESTING.md 不同路径，易混为重复件但实非同一物｜机械补全：基目录/展开规则→.superpowers/sdd', completed=True),
    DocOwner(path='.superpowers/sdd/2026-09-21-boards/', board='B10', fid='', currency='过程件', basis='代码侧目录级过程/工程件：十板块文档体系波席报目录（同 §4 兄弟波次行：过程件→B10）', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-21-unify-wave/', board='B10', fid='', currency='过程件', basis='代码侧目录级过程/工程件：中央调度层统一波席报/裁定/台账目录（同 §4 兄弟波次行：过程件→B10）', completed=False),
    DocOwner(path='.superpowers/sdd/2026-09-22-taxonomy/', board='B10', fid='', currency='过程件', basis='代码侧目录级过程/工程件：本轮规格统一波席报/基线/普查目录（同 §4 兄弟波次行：过程件→B10）', completed=False),
    DocOwner(path='docs/templates/', board='B10', fid='', currency='工程件', basis='代码侧目录级过程/工程件：文档模板体系工程件（唯一模板源，随 scripts/doc_templates.py 常驻；治理面归 B10）', completed=False),
)

#: 文件级条目（分类表逐行投影）。
DOC_OWNERSHIP: tuple[DocOwner, ...] = (
    DocOwner(path='AGENTS.md', board='B10', fid='', currency='现行权威(2026-09-20 入库, 顶部横幅 09-21 指向 FIXWAVE)', basis='顶部自带「接手必读」链, 是全局入口与规则源, 不是板块正文', completed=False),
    DocOwner(path='COMMANDS.md', board='B02', fid='', currency='现行权威(人读版命令手册, 09-20)', basis='自述「与 /bot help 同一口径」, 且指向 command-catalog 全量目录', completed=False),
    DocOwner(path='DESIGN-SPEC.md', board='B08', fid='', currency='现行权威(自述唯一根部视觉/质量入口, 被 verify_hashes 钉)', basis='文件头自证被 tests/verify_hashes.py SHA-256 清单纳入', completed=False),
    DocOwner(path='HANDOFF-FIXWAVE-20260921.md', board='B10', fid='', currency='现行权威(09-21 冷启动第一入口, untracked)', basis='AGENTS.md 顶部横幅点名「优先于下方各条」', completed=False),
    DocOwner(path='HANDOFF-NEXT.md', board='B10', fid='', currency='已失效(AGENTS.md 明示「已被上条取代为历史」; 09-15 首提交)', basis='交接链已由 FIXWAVE/V21R6 接手, 顶部自带「下方属历史批次」声明', completed=False),
    DocOwner(path='HANDOFF-PROMPT-20260921.md', board='B10', fid='', currency='现行权威(09-21 贴给下一 AI 的提示词, untracked)', basis='自述「与 AGENTS/HANDBOOK 冲突以它们为准」', completed=False),
    DocOwner(path='HANDOFF-SESSIONS-unify-audit-20260919.md', board='', fid='', currency='历史证据(统一性审查三会话归档, 09-20 untracked)', basis='自述为审查全量归档, 正文已蒸馏, 原件在 design 目录', completed=False),
    DocOwner(path='HANDOFF-V21R4-20260918.md', board='B10', fid='', currency='历史证据(v21r2→r4 收尾, 顶部有 v21r5 增量指针)', basis='自述「截至 r4, r5 改动未含」, 已被 R5/R6 交接取代', completed=False),
    DocOwner(path='HANDOFF-V21R4-B-20260918.md', board='B01', fid='', currency='历史证据(后端协议波交接)', basis='自述是 backend-protocol-plan.md 的交接版, 规格件已在 docs/design', completed=False),
    DocOwner(path='HANDOFF-V21R4-F-20260918.md', board='B08', fid='', currency='历史证据(前端渲染扩展波交接)', basis='自述是 frontend-render-expansion-plan.md 的交接版', completed=False),
    DocOwner(path='HANDOFF-V21R5-20260920.md', board='B02', fid='', currency='历史证据但含现役改动清单(r4-B 波总交接)', basis='逐席证据在 docs/design/v2*.md, 本文件是其蒸馏', completed=False),
    DocOwner(path='HANDOFF-V21R6-TESTING.md', board='B10', fid='', currency='现行权威(测试验收 AI 入口, 09-21 untracked)', basis='AGENTS.md 顶部「测试验收 AI 入口」点名此文件', completed=False),
    DocOwner(path='HANDOVER-TTS-GH-20260920.md', board='B06', fid='', currency='现行权威(TTS 统一波 G+H 契约/传输层, 09-21)', basis='自述「穷尽版 v2, HEAD=9d758a5 全在 git」', completed=False),
    DocOwner(path='README.md', board='B10', fid='', currency='现行权威(人类门面, 09-14 起)', basis='唯一面向人类的项目门面', completed=False),
    DocOwner(path='REVIEW-WORKFLOW.md', board='B10', fid='', currency='现行权威(评审规范, 09-15)', basis='流程规范, 未见他文取代', completed=False),
    DocOwner(path='V21-UPDATE-LOG.md', board='', fid='', currency='历史证据(V2.1 会话更新日志 09-17/18)', basis='波次日志, 待办已被 task_plan/FIXWAVE 换页声明取代', completed=False),
    DocOwner(path='WORKSPACE_GUIDE.md', board='B10', fid='', currency='现行权威(工作区引导, 09-15)', basis='与 README 存在「目录导览」重复', completed=False),
    DocOwner(path='docs/CODE-MAP.md', board='B10', fid='', currency='现行权威(导航件, 09-20)', basis='自述「导航件不复制正文」, audit-20260921 明确以它避免副本', completed=False),
    DocOwner(path='docs/HANDBOOK.md', board='B10', fid='', currency='现行权威(历史总账+单一活文档, 09-20)', basis='体量最大且自带权威链终裁, 与新 boards 存在双事实源风险', completed=False),
    DocOwner(path='docs/HANDOVER-2026-09-15.md', board='B01', fid='', currency='已失效(顶部有 09-17 指针横幅取代)', basis='自述「当前交接见 HANDOFF-NEXT」, 后者又已失效', completed=False),
    DocOwner(path='docs/README.md', board='B10', fid='', currency='现行权威(docs 索引, 09-21 由 T124 席补登)', basis='唯一 docs 索引, 且被链接完整性门覆盖', completed=False),
    DocOwner(path='docs/THIRD_PARTY_NOTICES.md', board='B08', fid='', currency='现行权威(09-21 追加 zhconv)', basis='自述「第三方出处唯一记录」, 许可证合规件', completed=False),
    DocOwner(path='docs/acceptance-manual.md', board='B10', fid='', currency='现行权威(接入与验收手册, 09-21)', basis='操作性手册, 与 snowluma-setup/napcat-setup 有重复', completed=False),
    DocOwner(path='docs/affinity-design.md', board='B03', fid='', currency='部分失效(v4 数值表被 v7 取代; 档位/红线仍权威)', basis='文件头自带权威链: 「§2/§3 步长数值已被 affinity-v7-design.md 取代」', completed=False),
    DocOwner(path='docs/ai-kb-operations-manual.md', board='B09', fid='', currency='现行权威(知识库入库说明书, 09-09)', basis='与 ai-setup-knowledge-pack 互为「说明书/全集」, 有内容重复', completed=False),
    DocOwner(path='docs/ai-setup-knowledge-pack.md', board='B09', fid='', currency='现行权威(搭建知识全集, 09-07 首提交 09-21 更新)', basis='自述「本文档是 ai-kb-operations-manual 的完整展开源」', completed=False),
    DocOwner(path='docs/audit-20260921-commands.md', board='B10', fid='', currency='现行(真机验收清单, 09-21 untracked)', basis='配套 audit §9, 验收动作件', completed=False),
    DocOwner(path='docs/audit-20260921-decisions.md', board='B09', fid='', currency='现行(待拍板清单, 09-21 untracked)', basis='面向用户的大白话裁决件, 技术细节指向 audit 主件', completed=False),
    DocOwner(path='docs/audit-20260921.md', board='', fid='', currency='现行权威但为审计结论件(09-21 untracked)', basis='自约束「避免制造第 N 份副本」; §0.4/§9 才是现役结论', completed=False),
    DocOwner(path='docs/auto-facts.md', board='B10', fid='', currency='生成物(机器所有勿手改, 09-15)', basis='被 tests/test_cross_validation_gates.py 常驻比对, 动它须先改门', completed=False),
    DocOwner(path='docs/codebase-slim-plan.md', board='', fid='', currency='已失效倾向(提案未实施, 09-13 数据)', basis='自述「本文件不含已执行改动, 待裁决后归档」', completed=False),
    DocOwner(path='docs/command-catalog.md', board='B02', fid='', currency='生成物(现行, scripts/command_catalog.py --write)', basis='文件头标注自动生成且被 doc_sync/哈希门禁钉住', completed=False),
    DocOwner(path='docs/config-catalog-full.md', board='B09', fid='', currency='生成物/半自动(09-20)', basis='权威源声明为 config.py, 手写目录有漂移风险', completed=False),
    DocOwner(path='docs/control-plane-provider-and-usage-requirements-2026-09-05.md', board='B09', fid='', currency='历史需求件(09-05「尚未进入实现」)', basis='状态自述未实现, 但 control_plane 已建成', completed=False),
    DocOwner(path='docs/db-owners.md', board='B04', fid='', currency='现行权威(09-12 grep 登记, 09-21 更新)', basis='「只登记不改迁移」, 与各域存储文档交叉', completed=False),
    DocOwner(path='docs/design/COMPACT-CHECKPOINT.md', board='B10', fid='', currency='现行(续接检查点, 顶部滚动)', basis='首行「最新, 优先于旧交接正文」; AGENTS 控制面校正段点名它为唯一事实页', completed=False),
    DocOwner(path='docs/design/affinity-v7-design.md', board='B03', fid='', currency='现行权威(U, 09-21 头注自证取代 v4/v5 数值)', basis='首行「本文件取代 docs/affinity-design.md 的数值算法部分」', completed=False),
    DocOwner(path='docs/design/audit-20260919-unify-wave.md', board='B10', fid='', currency='历史证据(09-19 统一收尾波独立审计)', basis='自述「独立第三方审计(非交付席自报)」, 后继为 09-20 U1–U24 波与 audit-20260921｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U1-invest.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U10-gate.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U11b-sec.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U13-db.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U17-campus-wire.md', board='B07', fid='', currency='历史证据但**被搜索引用**', basis='AGENTS #43⑤ 明文以「搜 U17-CAMPUS-WIRE」为摘牌指令｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U2-proto.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U20-cp.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U24-decision.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U3-outbound.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U4-dispatch.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U5-arch.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U6-config.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U7-command.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-U9-function.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/audit-20260920-unify-summary.md', board='B10', fid='', currency='历史证据(只读审计席位日志)', basis='各件首行自述「席位性质: 只读审计, 唯一可写文件=本文件」; summary 自述「合并者汇编, 非新增审计」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/backend-v2-acceptance-matrix.md', board='B10', fid='', currency='现役但**六列待回填**(U)', basis='v21r4-B B1 席(MAT)程序化回填（数以该席 §三.1 为准）, not_wired 口径见其 §三.1', completed=False),
    DocOwner(path='docs/design/backend-v2-implementation-guide.md', board='B02', fid='', currency='现行权威(实施合同, U)', basis='AGENTS.md 顶部与 docs/核心要求.md 双点名为权威链', completed=False),
    DocOwner(path='docs/design/backend-v2-product-extensions.md', board='B03', fid='', currency='现行权威(合同补充件, U)', basis='自述「补充主规范, 对应验收矩阵」', completed=False),
    DocOwner(path='docs/design/capability-orchestration-adoption-spec.md', board='B02', fid='', currency='现行权威(规格, Wave 1–4 未做, U)', basis='WP8-design 席位自述「只出文档, 本轮零代码改动」', completed=False),
    DocOwner(path='docs/design/central-decision-engine.md', board='B02', fid='', currency='已失效(状态=规格稿未实现, T 09-13)', basis='文件头状态行自证未实现; BOT_DECISION_ENGINE_MODE 仍 legacy_only', completed=False),
    DocOwner(path='docs/design/control-plane-api.md', board='B09', fid='', currency='历史规格(B4, T 09-12 未实现)', basis='状态自述「设计规格, 本轮不含实现代码」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/control-plane-core-status.md', board='B09', fid='', currency='现行权威(唯一事实页, U)', basis='AGENTS「控制面接手校正」段点名｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/control-plane-events.md', board='B09', fid='', currency='现行协议(U)', basis='自述「当前实现边界」+ 指向 COMPACT-CHECKPOINT｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/control-plane-metrics.md', board='B09', fid='', currency='现行协议(U)', basis='同上｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/control-plane-registry.md', board='B09', fid='', currency='现行契约(U)', basis='AGENTS 最新串行增量段点名｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/control-plane-services.md', board='B09', fid='', currency='现行边界件(U)', basis='自述「记录当前实现边界, 不能替代发布验收」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/control-plane-workspaces.md', board='B09', fid='', currency='现行边界件(U)', basis='自述「记录当前实现边界, 不能替代发布验收」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/divination-consolidation-20260921.md', board='B06', fid='', currency='现行权威(收编判定, U)', basis='引用户裁定 11.C 为判据, WP9 实施依据', completed=False),
    DocOwner(path='docs/design/emergency-alert-taxonomy-20260921.md', board='B05', fid='', currency='现行权威(唯一权威规格, U)', basis='首行「本件是唯一权威: 代码从这里派生, 不反过来」', completed=False),
    DocOwner(path='docs/design/emergency-info-card-spec-20260920.md', board='B08', fid='', currency='历史施工图(T 09-20)', basis='自述「本文是施工图 + diff 原文, 不是实施」', completed=False),
    DocOwner(path='docs/design/emergency-info-enablement-20260920.md', board='B05', fid='', currency='现行权威(上线操作单, U)', basis='AGENTS #46 明文登记该节; 但其「三重门」旧口径需按 #46 改写', completed=False),
    DocOwner(path='docs/design/emergency-info-outbound-gate-spec-20260920.md', board='B08', fid='', currency='现行规格(不写码, T 09-20)', basis='首行「B4-spec … 规格, 不写码」', completed=False),
    DocOwner(path='docs/design/emergency-info-registration-runbook-20260920.md', board='B05', fid='', currency='历史施工图(口径已被 #46 覆盖, T 09-20)', basis='AGENTS #45 称其「施工图唯一权威」, #46 裁定 3.B 令其 §5-钉死②第三腿作废', completed=False),
    DocOwner(path='docs/design/emergency-info-unify-spec-20260920.md', board='B05', fid='', currency='现行规格(B11 统一规格, T 09-20)', basis='自述「只读现状 + 成文形状」, 未见后继取代', completed=False),
    DocOwner(path='docs/design/emergency-info-unify-summary-20260919.md', board='B05', fid='', currency='历史证据(A 波收尾, T 09-20)', basis='波次收尾件, 后继为 wave-final 终验', completed=False),
    DocOwner(path='docs/design/emergency-info-unify-wave-final-20260920.md', board='B05', fid='', currency='历史证据(INTG-1 独立终验, T 09-20)', basis='自述「给用户的独立判定」, 一次性裁决件', completed=False),
    DocOwner(path='docs/design/file-transfer-gateway.md', board='B08', fid='', currency='历史规格(B3 Phase-1, T 09-12)', basis='AGENTS 第四部分记 file_gateway 仅 Phase-1', completed=False),
    DocOwner(path='docs/design/fstring-card-dom-spec.md', board='B08', fid='', currency='**部分实施 + 被哈希钉**', basis='同上 MANIFEST + AGENTS #26 记为「未实施待裁决」', completed=False),
    DocOwner(path='docs/design/link-unification-audit-20260920.md', board='B10', fid='', currency='历史证据(全仓链接归一审计)', basis='时点快照件, 引用前须重定位行号(自述)｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/llm-billing-ledger.md', board='B09', fid='', currency='历史规格(B5, T 09-12)', basis='状态自述未实现, 实际 ledger.py 已建成 → 存在双源冲突', completed=False),
    DocOwner(path='docs/design/media-digest-layer.md', board='B08', fid='', currency='现行规格(蓝图, T 09-20)', basis='T107 自述「方案件零施工」', completed=False),
    DocOwner(path='docs/design/memory-reflection-v2-design.md', board='B04', fid='', currency='现行权威(设计, U 09-21)', basis='首行绑定 WP6; marks 命中「已失效」是其引用旧键形所致, 非本文失效', completed=False),
    DocOwner(path='docs/design/outbound-template-unification-spec.md', board='B08', fid='', currency='现行规格(**待用户过目, 未开工**)', basis='状态行自述「待用户过目, 未开工」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/r18-taxonomy-20260920.md', board='B03', fid='', currency='现行权威(裁定清单 memo, U)', basis='AGENTS #43 点名此件为硬线唯一例外记录', completed=False),
    DocOwner(path='docs/design/render-pipeline-optimization-spec.md', board='B08', fid='', currency='**部分实施 + 被哈希钉**', basis='`tests/verify_hashes.py` MANIFEST 含本件(改动须 `--write` 重录)', completed=False),
    DocOwner(path='docs/design/tts-audit-20260919.md', board='B06', fid='', currency='历史证据(审计, T 09-19)', basis='与 tts-handover 同期同域, 结论已入契约层', completed=False),
    DocOwner(path='docs/design/tts-contract-layer.md', board='B06', fid='', currency='现行权威(Wave G 契约层, T 09-20)', basis='AGENTS #44 记其为规格真身且 T99 首次入库', completed=False),
    DocOwner(path='docs/design/tts-handover-20260919.md', board='B06', fid='', currency='历史证据为主(交接长文, T 09-20; 含现役坑)', basis='与 HANDOVER-TTS-GH-20260920.md(自称穷尽版 v2)构成新旧两份同事实源', completed=False),
    DocOwner(path='docs/design/unify-audit-20260919/AVT1-impl.md', board='B08', fid='', currency='过程件(bot 身份可参数化 / 全站品牌胶囊三面 / 契约锁补真 / 视觉整改 / 渲染+前端敌对审计 / 知识路径调查)', basis='AVT1/CAP1/CAP2/VIS1 首行 `Status: DONE` = 施工完; CAPFIX 首行 `Status: STARTED` = **未收口即停笔**｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/CAP1-impl.md', board='B08', fid='', currency='过程件(bot 身份可参数化 / 全站品牌胶囊三面 / 契约锁补真 / 视觉整改 / 渲染+前端敌对审计 / 知识路径调查)', basis='AVT1/CAP1/CAP2/VIS1 首行 `Status: DONE` = 施工完; CAPFIX 首行 `Status: STARTED` = **未收口即停笔**｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/CAPFIX-impl.md', board='B08', fid='', currency='过程件(bot 身份可参数化 / 全站品牌胶囊三面 / 契约锁补真 / 视觉整改 / 渲染+前端敌对审计 / 知识路径调查)', basis='AVT1/CAP1/CAP2/VIS1 首行 `Status: DONE` = 施工完; CAPFIX 首行 `Status: STARTED` = **未收口即停笔**｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/COPY-V2-C2-C4.md', board='B03', fid='', currency='半过程件(出站文案 v2 批次单 + 文风锚点册 + 六份变体稿)', basis='各件头注给出落地文件真身路径, 可直接核对是否已灌｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/COPY-V2-C5.md', board='B03', fid='', currency='半过程件(出站文案 v2 批次单 + 文风锚点册 + 六份变体稿)', basis='各件头注给出落地文件真身路径, 可直接核对是否已灌｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/COPY-V2-voice-brief.md', board='B03', fid='', currency='半过程件(出站文案 v2 批次单 + 文风锚点册 + 六份变体稿)', basis='各件头注给出落地文件真身路径, 可直接核对是否已灌｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F12-routing-ia.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F14-card-ia.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F22-render-rollout-plan.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F23-frontend-testable-draft.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F24-doc-reconciliation.md', board='B08', fid='', currency='历史证据(修复制品/实施台账/独立复算/对账单)', basis='F21/F17 自述「敌对性复核」= 二次审计件｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F3-webui-pages-a11y.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F5-card-render-tokens.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/F8-webui-performance.md', board='B08', fid='', currency='历史证据(F 系**只读快照审计**，逐件自述「快照声明 + date 实跑」)', basis='每件首行「快照声明」自证只读; 行号已随 09-20/21 改树漂移｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/FRONTEND-AUDIT.md', board='B10', fid='', currency='本波「唯一读数入口」总账 + 接手提示词(历史)', basis='HANDOFF-PROMPT 自述「先读 FRONTEND-AUDIT(唯一读数入口)」→ 两件互指, 移树须成对｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/HANDOFF-PROMPT.md', board='B10', fid='', currency='本波「唯一读数入口」总账 + 接手提示词(历史)', basis='HANDOFF-PROMPT 自述「先读 FRONTEND-AUDIT(唯一读数入口)」→ 两件互指, 移树须成对｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/K1-knowledge-paths.md', board='B08', fid='', currency='过程件(bot 身份可参数化 / 全站品牌胶囊三面 / 契约锁补真 / 视觉整改 / 渲染+前端敌对审计 / 知识路径调查)', basis='AVT1/CAP1/CAP2/VIS1 首行 `Status: DONE` = 施工完; CAPFIX 首行 `Status: STARTED` = **未收口即停笔**｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/OUTBOUND-COPY-AUDIT.md', board='B08', fid='', currency='现役偏旧(出站文案全量审核 + 模板全量清单, 09-20 时点)', basis='自述「行号=当时快照, 引用前重定位」｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/OUTBOUND-TEMPLATES-FULL.md', board='B08', fid='', currency='现役偏旧(出站文案全量审核 + 模板全量清单, 09-20 时点)', basis='自述「行号=当时快照, 引用前重定位」｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/PERF1-fix1.md', board='B09', fid='', currency='过程件(日志尾流页 + 记忆图 canvas 性能实做与两轮修复)', basis='首行「席别: PERF1* 实施席」｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/PERF1-impl.md', board='B09', fid='', currency='过程件(日志尾流页 + 记忆图 canvas 性能实做与两轮修复)', basis='首行「席别: PERF1* 实施席」｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/R5-fix1.md', board='B08', fid='', currency='过程件(**R5-fix2 编号缺件**, 全目录无该文件)', basis='三件互相引用 fix round 1/5, 但 fix2 不在盘 ⇒ 波次未连续或该席零产出｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/R5-impl.md', board='B08', fid='', currency='过程件(**R5-fix2 编号缺件**, 全目录无该文件)', basis='三件互相引用 fix round 1/5, 但 fix2 不在盘 ⇒ 波次未连续或该席零产出｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/S8-render-webui.md', board='B08', fid='', currency='过程件(bot 身份可参数化 / 全站品牌胶囊三面 / 契约锁补真 / 视觉整改 / 渲染+前端敌对审计 / 知识路径调查)', basis='AVT1/CAP1/CAP2/VIS1 首行 `Status: DONE` = 施工完; CAPFIX 首行 `Status: STARTED` = **未收口即停笔**｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/UNI1-fix1.md', board='B08', fid='', currency='过程件(前端「同一判据四套实现」收口 + 对账门补强)', basis='各件头注指 `.superpowers/sdd/FRONTEND-AUDIT/review-UNI1-report.md`｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/UNI1-impl.md', board='B08', fid='', currency='过程件(前端「同一判据四套实现」收口 + 对账门补强)', basis='各件头注指 `.superpowers/sdd/FRONTEND-AUDIT/review-UNI1-report.md`｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/unify-audit-20260919/VIS1-impl.md', board='B08', fid='', currency='过程件(bot 身份可参数化 / 全站品牌胶囊三面 / 契约锁补真 / 视觉整改 / 渲染+前端敌对审计 / 知识路径调查)', basis='AVT1/CAP1/CAP2/VIS1 首行 `Status: DONE` = 施工完; CAPFIX 首行 `Status: STARTED` = **未收口即停笔**｜机械补全：基目录/展开规则→docs/design/unify-audit-20260919', completed=True),
    DocOwner(path='docs/design/v21-affinity-fix-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-autosync-fix-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-controlplane-fix-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-risk-red-report.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-risk678-fix-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s0-baseline.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s0-inventory.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s0-mapping.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s1-sandbox-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s11-schedule-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s2-contracts-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s5-billing-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21-s5-events-log.md', board='B10', fid='', currency='过程件(V2.1 波 A1–A14 席)', basis='每件首行标「席位: A*/S*」+ 波次已收官, 结论在 AGENTS #37–#40 草案与 HANDBOOK｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-COORDINATION.md', board='B10', fid='', currency='已失效(波次并发协调表, 顶部滚动)', basis='波次协调件, 后继为 v21r4-b-coordination / v21r5-coordination 同型件', completed=False),
    DocOwner(path='docs/design/v21r2-acceptance-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-aff-replay-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-aff-replay-report.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-agents-ledger-draft.md', board='B10', fid='', currency='已失效(草案, 均已套用入正式台账)', basis='AGENTS 顶部明文「本文件 #37-#40 台账草案在 docs/design/v21r2-agents-ledger-draft.md」→ 归档前须先补该指针', completed=False),
    DocOwner(path='docs/design/v21r2-command-spec-entries-1.md', board='B02', fid='', currency='部分现役(命令格式统一规格 v1 + 附录A盘点)', basis='规格「文档先行零代码」; v21r4-command-format-review 是其评审后继｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-command-spec-entries-3.md', board='B02', fid='', currency='部分现役(命令格式统一规格 v1 + 附录A盘点)', basis='规格「文档先行零代码」; v21r4-command-format-review 是其评审后继｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-command-spec-inventory.md', board='B02', fid='', currency='部分现役(命令格式统一规格 v1 + 附录A盘点)', basis='规格「文档先行零代码」; v21r4-command-format-review 是其评审后继｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-command-spec.md', board='B02', fid='', currency='部分现役(命令格式统一规格 v1 + 附录A盘点)', basis='规格「文档先行零代码」; v21r4-command-format-review 是其评审后继', completed=False),
    DocOwner(path='docs/design/v21r2-dispatch-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-ep1-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-handbook-sync-draft.md', board='B10', fid='', currency='已失效(草案, 均已套用入正式台账)', basis='AGENTS 顶部明文「本文件 #37-#40 台账草案在 docs/design/v21r2-agents-ledger-draft.md」→ 归档前须先补该指针｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-legacy-manifest-draft.md', board='B10', fid='', currency='已失效(草案, 均已套用入正式台账)', basis='AGENTS 顶部明文「本文件 #37-#40 台账草案在 docs/design/v21r2-agents-ledger-draft.md」→ 归档前须先补该指针｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-matrix-backfill-draft.md', board='B10', fid='', currency='已失效(草案, 均已套用入正式台账)', basis='AGENTS 顶部明文「本文件 #37-#40 台账草案在 docs/design/v21r2-agents-ledger-draft.md」→ 归档前须先补该指针｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r1-llmroute-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r2-lifecycle-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r3-stall-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r4-affinity-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r5-hotzone-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r6-copy-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r7-contentroute-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-r8-crash-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-plan.md', board='B10', fid='', currency='现行施工图(domains/ 重组, U)', basis='二十余份 `v21r2-reorg-w*-log.md` 一致以它为「施工图」', completed=False),
    DocOwner(path='docs/design/v21r2-reorg-w10-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w11-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w12-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w13-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w13b-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w14-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w16-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w1a-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w2-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w3-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w4-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w5-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w6-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w7-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w8-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-w9-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-wc1-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-wc2-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-wc3-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-wc4-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-wc5-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-woc-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-reorg-wpa1-log.md', board='B10', fid='', currency='过程件(板块重组 RW* 席, 一域一件)', basis='各件首行「席位: RW*」且同引 v21r2-reorg-plan.md 为施工图｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-repair-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-ret1-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-rk4-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-rp-style-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s10-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s11-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s12-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s14-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s15-pregate-report.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s8-kb-db-teach-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-s9-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-search-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-shim-retirement-inventory.md', board='B10', fid='', currency='现行施工图(EP1 机核, U)', basis='头注「只读产出·退役施工图」, RET1/2/3/RET2B-PREP 各席同引', completed=False),
    DocOwner(path='docs/design/v21r2-v1-persona-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-v2-memory-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r2-wire-log.md', board='B10', fid='', currency='过程件(v21r2 后端波席位日志)', basis='首行一律「席位: X 席」; AGENTS #42 记「逐席报告」性质｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r3-core-chain-audit.md', board='B08', fid='', currency='历史证据(核心链路排查 + 渲染统一方案 + 垫片退役预研)', basis='AGENTS #41 记 SHIMRET「本波次不执行」→ 预研件非施工件', completed=False),
    DocOwner(path='docs/design/v21r3-render-closing-spec.md', board='B08', fid='', currency='现行权威(wave-2 唯一施工规格, U)', basis='自述「唯一施工规格」', completed=False),
    DocOwner(path='docs/design/v21r3-render-shim-retirement.md', board='B08', fid='', currency='历史证据(核心链路排查 + 渲染统一方案 + 垫片退役预研)', basis='AGENTS #41 记 SHIMRET「本波次不执行」→ 预研件非施工件｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r3-render-unification-plan.md', board='B08', fid='', currency='历史证据(核心链路排查 + 渲染统一方案 + 垫片退役预研)', basis='AGENTS #41 记 SHIMRET「本波次不执行」→ 预研件非施工件｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-L41-decision-memo.md', board='B04', fid='', currency='已失效(L41 由 v21r4-B WIRE-SVC 明确「不接」, 预案≠授权)', basis='两文件头注自证「不构成实施授权」; AGENTS #42 ⑤ 记 L41 仍 not_wired｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-L60-立项书.md', board='B04', fid='', currency='现役待裁(立项书, 开放 5/6/7 条待用户裁)', basis='AGENTS #42 ⑤ 记三立项书各带开放裁决条｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-L71-立项书.md', board='B04', fid='', currency='现役待裁(立项书, 开放 5/6/7 条待用户裁)', basis='AGENTS #42 ⑤ 记三立项书各带开放裁决条｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-L74-立项书.md', board='B04', fid='', currency='现役待裁(立项书, 开放 5/6/7 条待用户裁)', basis='AGENTS #42 ⑤ 记三立项书各带开放裁决条｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-CHARTER-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-DIRECT-PLAN-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-DOC-SYNC-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-DOCS-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-HANDBOOK-SYNC-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-INTEGRATE-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-L41-PLAN-log.md', board='B04', fid='', currency='已失效(L41 由 v21r4-B WIRE-SVC 明确「不接」, 预案≠授权)', basis='两文件头注自证「不构成实施授权」; AGENTS #42 ⑤ 记 L41 仍 not_wired｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-LEDGER-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-LEGACY-FIX-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-LIVE-TOOL-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-MAT-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-MEM-DEC-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-PORT-PLAN-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-QA-PROBE-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-REG-REFRESH-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-REM-DAWN-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-REM-EVE-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-RET2B-PREP-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-RET2b-R-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-RET3-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-RK5-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-RWC5-b-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-RWC6-b-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-S0-COLLECT-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-S0-ROOT-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-TOKEN-AUDIT-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-WIRE-DIRECT-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-WIRE-SVC-log.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-coordination.md', board='B10', fid='', currency='过程件(v21r4-B 并发波断点续跑依据)', basis='首行「席位: X」+ 自述「断点续跑依据」; AGENTS #42 逐席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-doc-sync-draft.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-qa-probe-report.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-restart-acceptance-checklist.md', board='B10', fid='', currency='已失效倾向(被 r5 版取代, U)', basis='后继件为 v21r5 同名录', completed=False),
    DocOwner(path='docs/design/v21r4-b-restart-gate-snapshot.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b-wave-snapshot.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-b2-direct-collect-plan.md', board='B02', fid='', currency='现行方案(DIRECT-PLAN, U)', basis='AGENTS #42 ⑨ 记其为收编设计真身', completed=False),
    DocOwner(path='docs/design/v21r4-b2-port-wiring-plan.md', board='B02', fid='', currency='待裁(方案材料, U)', basis='头注「不构成实施授权; 未确认前不得动码」', completed=False),
    DocOwner(path='docs/design/v21r4-b6-ledger-memo.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-command-format-review.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-kb-drift-explainer.md', board='B10', fid='', currency='过程件(波末草案/快照/调研备忘/评审材料/科普说明)', basis='自述多为「只读汇总零结论新增」｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r4-l41-exec-runbook.md', board='B04', fid='', currency='已失效(L41 由 v21r4-B WIRE-SVC 明确「不接」, 预案≠授权)', basis='两文件头注自证「不构成实施授权」; AGENTS #42 ⑤ 记 L41 仍 not_wired｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-BACKFILL-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-C-brief-final.md', board='B10', fid='', currency='过程件(协同登记 / 派遣简报 / 外部失败归因 / 跨会话交接包 / 对照基线快照)', basis='dossier 首行给出「9953 passed / 5 failed」实跑数, 属时点证据｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-CAMPUS-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-CAMPUSTH-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-CLEANUP-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-CRITFIX-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-DECISIONS-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-DOCS-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-DOCSCONSIST-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-DOSSIER-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-FIFTHR-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-FINALREVIEW-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-FIXN1-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-FIXN1B-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-FIXU17-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-HANDOFFADD-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-HELPSNAP-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-HYGIENE-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-INTIMACY-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-MINORSWEEP-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-POLICY-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-POLICYDOC-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-RENDERPROBE-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-RESTART-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-RESTARTCAMPUS-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-REVERIFY-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-REVIEW-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-TIMEOUT-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-U17CODE-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-U17DOCS-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-U17IMPL-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-U17PLAN-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-U17REVIEW-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-U17VERIFY-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-VERIF-log.md', board='B10', fid='', currency='过程件(v21r5 三任务波 + U17 收编链)', basis='首行「席位」+ AGENTS #43 全段按席引用｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-coordination.md', board='B10', fid='', currency='过程件(协同登记 / 派遣简报 / 外部失败归因 / 跨会话交接包 / 对照基线快照)', basis='dossier 首行给出「9953 passed / 5 failed」实跑数, 属时点证据｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-external-failure-dossier.md', board='B10', fid='', currency='过程件(协同登记 / 派遣简报 / 外部失败归因 / 跨会话交接包 / 对照基线快照)', basis='dossier 首行给出「9953 passed / 5 failed」实跑数, 属时点证据｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-frontend-handoff-package.md', board='B10', fid='', currency='过程件(协同登记 / 派遣简报 / 外部失败归因 / 跨会话交接包 / 对照基线快照)', basis='dossier 首行给出「9953 passed / 5 failed」实跑数, 属时点证据｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-help-registry-snapshot.md', board='B10', fid='', currency='过程件(协同登记 / 派遣简报 / 外部失败归因 / 跨会话交接包 / 对照基线快照)', basis='dossier 首行给出「9953 passed / 5 failed」实跑数, 属时点证据｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/v21r5-restart-acceptance-checklist.md', board='B10', fid='', currency='现行验收清单(U, 九节全码核实)', basis='AGENTS #43 明文指此件为验收权威', completed=False),
    DocOwner(path='docs/design/v21r5-u17-implementation-runbook.md', board='B07', fid='', currency='历史施工图(U17 已实施)', basis='其下游 U17-IMPL-3 席已按单施工完毕', completed=False),
    DocOwner(path='docs/design/visual-effects-catalog.md', board='B08', fid='', currency='**部分实施 + 被哈希钉**', basis='同上 MANIFEST; 自述「逐 E 号实施态」=半程件', completed=False),
    DocOwner(path='docs/design/webui-axonhub-adoption.md', board='B09', fid='', currency='现行规格(WebUI 一期/二期/采纳路线)', basis='AGENTS #41 记二期三页真数据已全部交付（比例以该席记录为准） → 规格与实况需对账｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/webui-dashboard-spec.md', board='B09', fid='', currency='现行规格(WebUI 一期/二期/采纳路线)', basis='AGENTS #41 记二期三页真数据已全部交付（比例以该席记录为准） → 规格与实况需对账｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/design/webui-pages2-spec.md', board='B09', fid='', currency='现行规格(WebUI 一期/二期/采纳路线)', basis='AGENTS #41 记二期三页真数据已全部交付（比例以该席记录为准） → 规格与实况需对账｜机械补全：基目录/展开规则→docs/design', completed=True),
    DocOwner(path='docs/external-runtime-access.md', board='B10', fid='', currency='现行权威(09-20)', basis='与 workspace-archive-policy 主题重复, 需去重', completed=False),
    DocOwner(path='docs/handover-c-20260913.md', board='B05', fid='', currency='历史证据(09-13 C 方向交接)', basis='波次交接, 内容已由 domains/finance 与 rendering-contract 覆盖', completed=False),
    DocOwner(path='docs/issue-ledger-p2-p3.md', board='B10', fid='', currency='部分现役(P2/P3 台账, 09-14)', basis='AGENTS.md 第六部分是索引, 本件是详情', completed=False),
    DocOwner(path='docs/napcat-setup.md', board='B01', fid='', currency='已失效(09-18 起协议端改 SnowLuma, 留作回滚)', basis='文件头自述「新接入不要再按本文操作」', completed=False),
    DocOwner(path='docs/nightly-ops-report-20260915.md', board='', fid='', currency='历史证据(09-15 夜间工程总报告)', basis='提交哈希基线 90274f5..4608235, 已被 HANDBOOK 吸收', completed=False),
    DocOwner(path='docs/pending-decisions.md', board='', fid='', currency='历史(09-14 聚合, 多数已被 09-21 decisions 取代)', basis='同源后继件为 audit-20260921-decisions.md', completed=False),
    DocOwner(path='docs/perf-optimization-plan.md', board='', fid='', currency='已失效(自述「历史测量档案, 不再更新」)', basis='顶部状态注记直接宣布非现行', completed=False),
    DocOwner(path='docs/rendering-contract.md', board='B08', fid='', currency='生成/契约双身份(09-20)', basis='自述单一事实源 theme_tokens.py, 机器形态=tests/test_rendering_contract.py', completed=False),
    DocOwner(path='docs/route-matrix.md', board='B02', fid='', currency='现行权威(09-20/09-21)', basis='与 command-catalog 生成物有重叠, 需以代码为准', completed=False),
    DocOwner(path='docs/search-api-adapters-2026-09-06.md', board='B05', fid='', currency='现役偏旧(09-06, Tavily/You/LangSearch 链)', basis='回退顺序等事实另有 config 键定义点', completed=False),
    DocOwner(path='docs/snowluma-setup.md', board='B01', fid='', currency='现行权威(09-20, 现役协议端)', basis='自述现行协议端; napcat-setup 的回滚件', completed=False),
    DocOwner(path='docs/standard-parse-card-acceptance.md', board='B05', fid='', currency='部分现役(09-01/09-07, 解析卡字段标准)', basis='配套实现文档已换代, 字段标准仍需核对是否漂移', completed=False),
    DocOwner(path='docs/superpowers/plans/2026-08-30-media-contract-and-parsers-zh.md', board='B05', fid='', currency='历史实施计划(09-07; 解析器 34 件已建成)', basis='首行「供执行代理使用: 必须使用 superpowers:…」= 一次性驱动计划', completed=False),
    DocOwner(path='docs/superpowers/plans/2026-08-30-music-backend-v2-zh.md', board='B06', fid='', currency='历史实施计划(09-07; 点歌 5 供应商已上线)', basis='同上形态', completed=False),
    DocOwner(path='docs/superpowers/plans/2026-08-30-subscription-v2-and-social-adapters-zh.md', board='B05', fid='', currency='历史实施计划(09-07; subscribe_v2 已建成)', basis='同上', completed=False),
    DocOwner(path='docs/superpowers/plans/2026-09-05-backend-core-slice-zh.md', board='B09', fid='', currency='历史实施计划(09-07)', basis='自述「REQUIRED SUB-SKILL: executing-plans」= 计划件', completed=False),
    DocOwner(path='docs/superpowers/plans/2026-09-06-defensive-context-compiler-plan.md', board='B03', fid='', currency='历史实施计划(09-06)', basis='与同目录 spec 配对, 成对移树', completed=False),
    DocOwner(path='docs/superpowers/plans/2026-09-12-shorekeeper-global-audit.md', board='B10', fid='', currency='历史实施计划(09-13)', basis='AGENTS 第七部分点名该 sdd 目录为 B 方向交接件', completed=False),
    DocOwner(path='docs/superpowers/specs/2026-08-29-social-music-backend-v2-design.md', board='B06', fid='', currency='历史设计规格(09-07)', basis='三份 08-29/08-30 件是同波 plan/spec 成对件', completed=False),
    DocOwner(path='docs/superpowers/specs/2026-09-06-defensive-context-compiler-design.md', board='B03', fid='', currency='历史设计规格(09-06)', basis='同上', completed=False),
    DocOwner(path='docs/superpowers/specs/2026-09-09-video-understanding-design.md', board='B06', fid='', currency='**现行待实施设计**(09-11; 视频理解 Media Registry)', basis='头注「待裁」+ 全仓未见 media registry 实施文档承接', completed=False),
    DocOwner(path='docs/usage-cache-price-fix-2026-09-18.md', board='B09', fid='', currency='历史证据(09-18 一次性修复记录, untracked)', basis='定点修复记录, 结论应在计费账本正文', completed=False),
    DocOwner(path='docs/workspace-archive-policy.md', board='B10', fid='', currency='现役但被取代倾向(08-28 起)', basis='与后者主题高度重叠', completed=False),
    DocOwner(path='docs/核心要求.md', board='B10', fid='', currency='现行权威(用户 mandate 逐字, 09-20 untracked)', basis='顶部指向 backend-v2-implementation-guide 为实施合同', completed=False),
    DocOwner(path='findings.md', board='B10', fid='', currency='过程件(本轮交接发现, 09-21 有追加)', basis='planning-with-files 会话产物, 内容已被 FIXWAVE §6 吸收', completed=False),
    DocOwner(path='report-T116.md', board='B06', fid='', currency='过程件(席位报告, 09-20 untracked)', basis='单席施工报告, 结论已落 docs/design/media-digest-layer.md', completed=False),
    DocOwner(path='report-T124.md', board='B10', fid='', currency='过程件(纯文档同步席, 09-20 untracked)', basis='已执行的文档同步动作, 无长期信息量', completed=False),
    DocOwner(path='审查结论与重构计划.md', board='', fid='', currency='历史证据(09-17 untracked, HEAD=90274f5 基线)', basis='基线 commit 早于 v21 全部波次', completed=False),
)

#: 分类表引用过、但路径已不存在的历史件（被归档/删除/改名），信息不丢。
DOC_OWNERSHIP_ARCHIVE: tuple[DocOwner, ...] = (
    DocOwner(path='COORDINATION.md', board='', fid='', currency='已失效(过程件, v21r2 并行批次席位登记, 09-20 untracked)', basis='历史行路径不可解析（处置:归档到归档包（路径以归档规程真身为准））', completed=False),
    DocOwner(path='progress.md', board='', fid='', currency='过程件(本轮进度, 09-21)', basis='历史行路径不可解析（处置:归档）', completed=False),
    DocOwner(path='task_plan.md', board='', fid='', currency='已失效(顶部自述「以下内容是历史计划, 不是现役进度」)', basis='历史行路径不可解析（处置:归档）', completed=False),
)
